app/home/forms.py
# coding:utf8
# author：GXR
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField
from wtforms.validators import DataRequired, EqualTo, Email, Regexp, ValidationError
from app.models import User
from flask import session


# 会员注册表单
class RegistForm(FlaskForm):
    name = StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称！')
        ],
        description='昵称',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入昵称！',
        }
    )
    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入邮箱！'),
            Email('邮箱格式不正确！')
        ],
        description='邮箱',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入邮箱！',
        }
    )
    phone = StringField(
        label='手机',
        validators=[
            DataRequired('请输入手机！'),
            Regexp('^(13[0-9]|14[579]|15[0-3,5-9]|16[6]|17[0135678]|18[0-9]|19[89])\\d{8}$', message='手机格式不正确！')
        ],
        description='手机',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入手机！',
        }
    )
    pwd = PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码！')
        ],
        description='密码',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入密码！',
        }
    )
    repwd = PasswordField(
        label='确认密码',
        validators=[
            DataRequired('请输入确认密码！'),
            EqualTo('pwd', message='两次密码不一致！')
        ],
        description='确认密码',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入确认密码！',
        }
    )
    submit = SubmitField(
        '注册',
        render_kw={
            'class': 'btn btn-lg btn-success btn-block'
        }
    )

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 1:
            raise ValidationError('昵称已存在！')

    def validate_email(self, field):
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError('邮箱已存在！')

    def validate_phone(self, field):
        phone = field.data
        user = User.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError('手机已存在！')


# 会员登录表单
class LoginForm(FlaskForm):
    name = StringField(
        label='账号',
        validators=[
            DataRequired('请输入账号！')
        ],
        description='账号',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入账号！',
        }
    )
    pwd = PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码！')
        ],
        description='密码',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入密码！',
        }
    )
    submit = SubmitField(
        '登陆',
        render_kw={
            'class': 'btn btn-lg btn-primary btn-block'
        }
    )


# 会员信息修改表单
class UserdetailForm(FlaskForm):
    name = StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称！')
        ],
        description='昵称',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入昵称！',
        }
    )
    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入邮箱！'),
            Email('邮箱格式不正确！')
        ],
        description='邮箱',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入邮箱！',
        }
    )
    phone = StringField(
        label='手机',
        validators=[
            DataRequired('请输入手机！'),
            Regexp('^(13[0-9]|14[579]|15[0-3,5-9]|16[6]|17[0135678]|18[0-9]|19[89])\\d{8}$', message='手机格式不正确！')
        ],
        description='手机',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入手机！',
        }
    )
    face = FileField(
        label='头像',
        validators=[
            DataRequired('请输入头像！'),
        ],
        description='头像',
    )
    info = TextAreaField(
        label='简介',
        validators=[
            DataRequired('请输入简介！')
        ],
        description='简介',
        render_kw={
            'class': 'form-control',
            'rows': '10',
        }
    )
    submit = SubmitField(
        '保存修改',
        render_kw={
            'class': 'btn btn-success'
        }
    )


# 会员修改密码表单
class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label='旧密码',
        validators=[
            DataRequired('请输入旧密码！')
        ],
        description='旧密码',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入旧密码！',
        }
    )
    new_pwd = PasswordField(
        label='新密码',
        validators=[
            DataRequired('请输入新密码！')
        ],
        description='新密码',
        render_kw={
            'class': 'form-control',
            'placeholder': '请输入新密码！',
        }
    )
    submit = SubmitField(
        '修改密码',
        render_kw={
            'class': 'btn btn-success',
        }
    )

    def validate_old_pwd(self, field):
        name = session['user']
        pwd = field.data
        user = User.query.filter_by(name=name).first()
        if not user.check_pwd(pwd):
            raise ValidationError('旧密码错误！')


# 会员评论表单
class CommentForm(FlaskForm):
    content = TextAreaField(
        label='内容',
        validators=[
            DataRequired('请输入内容！')
        ],
        description='内容',
        render_kw={
            'id': 'input_content',
            'rows': '10',
        }
    )
    submit = SubmitField(
        '提交评论',
        render_kw={
            'class': 'btn btn-success',
        }
    )

app/home/__init__.py
# coding:utf8
# author：GXR
from flask import Blueprint

home = Blueprint('home', __name__)

import app.home.views

app/home/views.py
# coding:utf8
# author：GXR
from . import home
from flask import render_template, redirect, url_for, flash, session, request, Response
from .forms import RegistForm, LoginForm, UserdetailForm, PwdForm, CommentForm
from app.models import User, Userlog, Comment, Moviecol, Preview, Tag, Movie
from functools import wraps
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from pypinyin import lazy_pinyin
from app import db, rd, app
import datetime
import uuid
import json
import os


# 登陆验证装饰器
def user_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user' not in session:
            return redirect(url_for('home.login', next=request.url))
        return f(*args, **kwargs)

    return decorated_function


# 修改文件名称
# def change_filename(filename):
#     fileinfo = os.path.splitext(filename)
#     filename = datetime.datetime.now().strftime("%Y%m%d%H%M%S") + '_' + uuid.uuid4().hex + fileinfo[-1]
#     return filename


# 会员注册
@home.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegistForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data['name'],
            email=data['email'],
            phone=data['phone'],
            pwd=generate_password_hash(data['pwd']),
            uuid=uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash('注册成功！', 'ok')
        return redirect(url_for('home.login'))
    return render_template('home/register.html', form=form)


# 会员登录
@home.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data['name']).first()
        if not user.check_pwd(data['pwd']):
            flash('密码错误！', 'err')
            return redirect(url_for('home.login'))
        session['user'] = user.name
        session['user_id'] = user.id
        userlog = Userlog(
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        flash('登陆成功！', 'ok')
        return redirect(url_for('home.index', page=1))
    return render_template('home/login.html', form=form)


# 会员退出
@home.route('/logout/')
@user_login_req
def logout():
    session.pop('user', None)
    session.pop('user_id', None)
    return redirect(url_for('home.login'))


# 会员中心
@home.route('/user/', methods=['GET', 'POST'])
@user_login_req
def user():
    # 当前登录用户
    if 'user_id' in session:
        user_now = User.query.get(session['user_id'])
    else:
        user_now = ''

    form = UserdetailForm()
    user = User.query.get(session['user_id'])
    form.face.validators = []
    if request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.face.data = user.face
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        # file_face = secure_filename(''.join(lazy_pinyin(form.face.data.filename)))

        if not os.path.exists(app.config['FACE_DIR']):
            os.makedirs(app.config['FACE_DIR'])
            os.chmod(app.config['FACE_DIR'], 'rw')
        # user.face = change_filename(file_face)
        user.face = form.face.data.filename
        form.face.data.save(app.config['FACE_DIR'] + user.face)

        name_count = User.query.filter_by(name=data['name']).count()
        if data['name'] != user.name and name_count == 1:
            flash('昵称已经存在！', 'err')
            return redirect(url_for('home.user'))

        email_count = User.query.filter_by(email=data['email']).count()
        if data['email'] != user.email and email_count == 1:
            flash('邮箱已经存在！', 'err')
            return redirect(url_for('home.user'))

        phone_count = User.query.filter_by(phone=data['phone']).count()
        if data['phone'] != user.phone and phone_count == 1:
            flash('手机已经存在！', 'err')
            return redirect(url_for('home.user'))

        user.name = data['name']
        user.email = data['email']
        user.phone = data['phone']
        user.info = data['info']
        db.session.add(user)
        db.session.commit()
        flash('修改成功！', 'ok')
        return redirect(url_for('home.user'))
    return render_template('home/user.html', form=form, user=user, user_now=user_now)


# 会员修改密码
@home.route('/pwd/', methods=['GET', 'POST'])
@user_login_req
def pwd():
    # 当前登录用户
    if 'user_id' in session:
        user_now = User.query.get(session['user_id'])
    else:
        user_now = ''

    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=session['user']).first()
        user.pwd = generate_password_hash(data['new_pwd'])
        db.session.add(user)
        db.session.commit()
        flash('修改密码成功，请重新登录！', 'ok')
        return redirect(url_for('home.logout'))
    return render_template('home/pwd.html', form=form, user_now=user_now)


# 会员评论记录
@home.route('/comments/<int:page>/', methods=["GET"])
@user_login_req
def comments(page=None):
    # 当前登录用户
    if 'user_id' in session:
        user_now = User.query.get(session['user_id'])
    else:
        user_now = ''

    if page is None:
        page = 1
    page_data = Comment.query.filter_by(
        user_id=session['user_id']
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=20)
    return render_template('home/comments.html', page_data=page_data, user_now=user_now)


# 会员登录日志
@home.route('/loginlog/<int:page>/', methods=["GET"])
@user_login_req
def loginlog(page=None):
    # 当前登录用户
    if 'user_id' in session:
        user_now = User.query.get(session['user_id'])
    else:
        user_now = ''

    if page is None:
        page = 1
    page_data = Userlog.query.filter_by(
        user_id=session['user_id']
    ).order_by(
        Userlog.addtime.desc()
    ).paginate(page=page, per_page=20)
    return render_template('home/loginlog.html', page_data=page_data, user_now=user_now)


# 会员添加收藏电影
@home.route('/moviecol/add/', methods=['GET'])
@user_login_req
def moviecol_add():
    mid = request.args.get('mid', '')
    uid = request.args.get('uid', '')
    moviecol_count = Moviecol.query.filter_by(
        movie_id=int(mid),
        user_id=int(uid)
    ).count()
    if moviecol_count == 1:
        data = dict(ok=0)
    if moviecol_count == 0:
        moviecol = Moviecol(
            movie_id=mid,
            user_id=uid
        )
        db.session.add(moviecol)
        db.session.commit()
        data = dict(ok=1)
    return json.dumps(data)


# 会员收藏电影列表
@home.route('/moviecol/<int:page>/', methods=["GET"])
@user_login_req
def moviecol(page=None):
    # 当前登录用户
    if 'user_id' in session:
        user_now = User.query.get(session['user_id'])
    else:
        user_now = ''

    if page is None:
        page = 1
    page_data = Moviecol.query.filter_by(
        user_id=session['user_id']
    ).order_by(
        Moviecol.addtime.desc()
    ).paginate(page=page, per_page=20)
    return render_template('home/moviecol.html', page_data=page_data, user_now=user_now)


# 首页传参
@home.route('/')
def index_page():
    return redirect(url_for('home.index', page=1))


# 电影首页
@home.route('/<int:page>/', methods=["GET"])
def index(page=None):
    # 当前登录用户
    if 'user_id' in session:
        user_now = User.query.get(session['user_id'])
    else:
        user_now = ''

    # 所有标签
    tag_list = Tag.query.all()
    # 分页数据
    page_data = Movie.query
    # 标签筛选
    tag = request.args.get('tag', 0)
    if int(tag) != 0:
        page_data = page_data.filter_by(tag_id=int(tag))
    # 星级筛选
    star = request.args.get('star', 0)
    if int(star) != 0:
        page_data = page_data.filter_by(star=int(star))
    # 时间筛选
    time = request.args.get('time', 0)
    if int(time) != 0:
        if int(time) == 1:
            page_data = page_data.order_by(
                Movie.addtime.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.addtime.asc()
            )
    # 播放量筛选
    pnum = request.args.get('pnum', 0)
    if int(pnum) != 0:
        if int(pnum) == 1:
            page_data = page_data.order_by(
                Movie.playnum.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.playnum.asc()
            )
    # 评论量筛选
    cnum = request.args.get('cnum', 0)
    if int(cnum) != 0:
        if int(cnum) == 1:
            page_data = page_data.order_by(
                Movie.commentnum.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.commentnum.asc()
            )
    # 分页
    if page is None:
        page = 1
    page_data = page_data.paginate(page=page, per_page=20)
    # URL参数
    p = dict(
        tag=tag,
        star=star,
        time=time,
        pnum=pnum,
        cnum=cnum,
    )
    return render_template('home/index.html', tag_list=tag_list, p=p, page_data=page_data, user_now=user_now)


# 电影预告
@home.route('/animation/')
def animation():
    preview_list = Preview.query.all()
    return render_template('home/animation.html', preview_list=preview_list)


# 电影搜索
@home.route('/search/<int:page>/', methods=["GET"])
def search(page=None):
    # 当前登录用户
    if 'user_id' in session:
        user_now = User.query.get(session['user_id'])
    else:
        user_now = ''
    if page is None:
        page = 1
    key = request.args.get('key', '')
    search_count = Movie.query.filter(
        Movie.title.ilike('%' + key + '%')
    ).count()
    page_data = Movie.query.filter(
        Movie.title.ilike('%' + key + '%')
    ).order_by(
        Movie.addtime.desc()
    ).paginate(page=page, per_page=20)
    page_data.key = key
    return render_template('home/search.html', key=key, page_data=page_data, search_count=search_count,

app/templates/home/animation.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>热映电影</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='animation/css/style.css') }}">
</head>
<body>
<!--轮播图 开始 -->
<div class="main_banner">
    <div class="main_banner_wrap">
        <canvas id="myCanvas" width="150" height="150"></canvas>
        <div class="main_banner_box" id="m_box">
            <a href="javascript:void(0)" class="banner_btn js_pre">
                <span class="banner_btn_arrow"><i></i></span>
            </a>
            <a href="javascript:void(0)" class="banner_btn btn_next js_next">
                <span class="banner_btn_arrow"><i></i></span>
            </a>
            <ul>
                {% for v in preview_list %}
                    <li id="imgCard{{ v.id - 1 }}">
                        <a href=""><span style="opacity:0;"></span></a>
                        <img src="{{ url_for('static',filename='uploads/preview/'+v.logo) }}"
                             style="width: 700px;height: 320px">
                        <p style="bottom:0">{{ v.title }}</p>
                    </li>
                {% endfor %}
            </ul>
            <!--火狐倒影图层-->
            <p id="rflt"></p>
            <!--火狐倒影图层-->
        </div>
        <!--序列号按钮-->
        <div class="btn_list">
            <span class="curr"></span><span></span><span></span><span></span><span></span>
        </div>
    </div>

</div>
<!--轮播图 结束 -->

<script type="text/javascript" src="{{ url_for('static',filename='animation/js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='animation/js/script.js') }}"></script>

</body>
</html>

app/templates/home/base_home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>好电影</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css') }}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block css %}
    {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index', page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename='base/images/logo.png') }}" style=" height:30px;">&nbsp;好电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span
                                class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index', page=1) }}"><span
                            class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                {% if not session['user'] %}
                    <li>
                        <a class="curlink" href="{{ url_for('home.login') }}"><span
                                class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for('home.register') }}"><span
                                class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                    </li>
                {% else %}
                    <li>
                        <a class="curlink" href="{{ url_for('home.logout') }}"><span
                                class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for('home.user') }}"><img
                                src="{{ url_for('static',filename='uploads/face/'+user_now.face) }}"
                                class="img-circle"
                                style="border:1px solid #abcdef;width: 30px;height: 30px">&nbsp;会员</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}
    {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <strong>友情链接</strong> :
                    <a href="http://www.newcoder.top" target="_blank">新码农</a> |
                    <a href="http://www.baidu.com" target="_blank">百度一下</a>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p>
                    <strong>Copyright &copy; 2019-2020</strong> |
                    <a href="{{ url_for('admin.index') }}" target="_blank">All Rights Reserved</a> |
                    <a href="{{ url_for('home.index',page=1) }}" target="_blank">goodsmovie.top</a> |
                    <a href="http://www.beian.miit.gov.cn/" target="_blank">冀ICP备18036301号-2</a>
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function () {
            var key = $("#key_movie").val();
            location.href = "{{ url_for('home.search', page=1) }}?key=" + key;
        });
    });
</script>
{% block js %}
{% endblock %}
</body>
</html>

app/templates/home/base_movie.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>好电影</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css') }}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block css %}
    {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index', page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename='base/images/logo.png') }}" style=" height:30px;">&nbsp;好电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span
                                class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index', page=1) }}"><span
                            class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                {% if not session['user'] %}
                    <li>
                        <a class="curlink" href="{{ url_for('home.login') }}"><span
                                class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for('home.register') }}"><span
                                class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                    </li>
                {% else %}
                    <li>
                        <a class="curlink" href="{{ url_for('home.logout') }}"><span
                                class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for('home.user') }}"><img
                                src="{{ url_for('static',filename='uploads/face/'+user_now.face) }}"
                                class="img-circle"
                                style="border:1px solid #abcdef;width: 30px;height: 30px">&nbsp;会员</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
{% block content %}
{% endblock %}
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <strong>友情链接</strong> :
                    <a href="http://www.newcoder.top" target="_blank">新码农</a> |
                    <a href="http://www.baidu.com" target="_blank">百度一下</a>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p>
                    <strong>Copyright &copy; 2019-2020</strong> |
                    <a href="{{ url_for('admin.index') }}" target="_blank">All Rights Reserved</a> |
                    <a href="{{ url_for('home.index',page=1) }}" target="_blank">goodsmovie.top</a> |
                    <a href="http://www.beian.miit.gov.cn/" target="_blank">冀ICP备18036301号-2</a>
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function () {
            var key = $("#key_movie").val();
            location.href = "{{ url_for('home.search', page=1) }}?key=" + key;
        });
    });
</script>
{% block js %}
{% endblock %}
</body>
</html>